from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import *
from PyQt5.QtWidgets import QTableWidget,QTableWidgetItem
from PyQt5.QtWidgets import *
import sys, requests
import json

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(770, 498)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 771, 501))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 20, 761, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.campoCodigo = QtWidgets.QLineEdit(self.tab)
        self.campoCodigo.setGeometry(QtCore.QRect(10, 100, 181, 21))
        self.campoCodigo.setObjectName("campoCodigo")
        self.campoCodigoBarras = QtWidgets.QLineEdit(self.tab)
        self.campoCodigoBarras.setGeometry(QtCore.QRect(200, 100, 181, 21))
        self.campoCodigoBarras.setObjectName("campoCodigoBarras")
        self.campoCorredor = QtWidgets.QLineEdit(self.tab)
        self.campoCorredor.setGeometry(QtCore.QRect(390, 100, 371, 21))
        self.campoCorredor.setObjectName("campoCorredor")
        self.campoDepartamento = QtWidgets.QLineEdit(self.tab)
        self.campoDepartamento.setGeometry(QtCore.QRect(250, 160, 291, 21))
        self.campoDepartamento.setObjectName("campoDepartamento")
        self.campoFornecedor = QtWidgets.QComboBox(self.tab)
        self.campoFornecedor.setGeometry(QtCore.QRect(550, 160, 211, 22))
        self.campoFornecedor.setObjectName("campoFornecedor")
        self.campoDataValidade = QtWidgets.QDateEdit(self.tab)
        self.campoDataValidade.setGeometry(QtCore.QRect(130, 160, 110, 22))
        self.campoDataValidade.setObjectName("campoDataValidade")
        self.campoDataEntrada = QtWidgets.QDateEdit(self.tab)
        self.campoDataEntrada.setGeometry(QtCore.QRect(10, 160, 110, 22))
        self.campoDataEntrada.setObjectName("campoDataEntrada")
        self.campoDescricao = QtWidgets.QLineEdit(self.tab)
        self.campoDescricao.setGeometry(QtCore.QRect(10, 220, 751, 21))
        self.campoDescricao.setObjectName("campoDescricao")
        self.campoGrupo = QtWidgets.QLineEdit(self.tab)
        self.campoGrupo.setGeometry(QtCore.QRect(10, 280, 181, 21))
        self.campoGrupo.setObjectName("campoGrupo")
        self.campoIdFuncionario = QtWidgets.QLineEdit(self.tab)
        self.campoIdFuncionario.setGeometry(QtCore.QRect(210, 280, 181, 21))
        self.campoIdFuncionario.setObjectName("campoIdFuncionario")
        self.campoMarca = QtWidgets.QLineEdit(self.tab)
        self.campoMarca.setGeometry(QtCore.QRect(410, 280, 141, 21))
        self.campoMarca.setObjectName("campoMarca")
        self.campoPreco = QtWidgets.QLineEdit(self.tab)
        self.campoPreco.setGeometry(QtCore.QRect(570, 280, 181, 21))
        self.campoPreco.setObjectName("campoPreco")
        self.campoTipo = QtWidgets.QLineEdit(self.tab)
        self.campoTipo.setGeometry(QtCore.QRect(600, 340, 151, 21))
        self.campoTipo.setObjectName("campoTipo")
        self.campoSecao = QtWidgets.QLineEdit(self.tab)
        self.campoSecao.setGeometry(QtCore.QRect(410, 340, 171, 21))
        self.campoSecao.setObjectName("campoSecao")
        self.campoResponsavel = QtWidgets.QComboBox(self.tab)
        self.campoResponsavel.setGeometry(QtCore.QRect(210, 340, 181, 22))
        self.campoResponsavel.setObjectName("campoResponsavel")
        self.campoPrecoPor = QtWidgets.QLineEdit(self.tab)
        self.campoPrecoPor.setGeometry(QtCore.QRect(10, 340, 181, 21))
        self.campoPrecoPor.setObjectName("campoPrecoPor")
        self.campoUnidade = QtWidgets.QLineEdit(self.tab)
        self.campoUnidade.setGeometry(QtCore.QRect(10, 390, 181, 21))
        self.campoUnidade.setObjectName("campoUnidade")
        self.labelTeste = QtWidgets.QLabel(self.tab)
        self.labelTeste.setEnabled(True)
        self.labelTeste.setGeometry(QtCore.QRect(200, 390, 201, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelTeste.setFont(font)
        self.labelTeste.setText("")
        self.labelTeste.setObjectName("labelTeste")
        self.botaoTestar = QtWidgets.QPushButton(self.tab)
        self.botaoTestar.setGeometry(QtCore.QRect(420, 390, 221, 23))
        self.botaoTestar.setObjectName("botaoTestar")
        self.botaoCadastrar = QtWidgets.QPushButton(self.tab)
        self.botaoCadastrar.clicked.connect(self.cadastrar_produto)
        self.botaoCadastrar.setGeometry(QtCore.QRect(660, 390, 91, 23))
        self.botaoCadastrar.setObjectName("botaoCadastrar")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 131, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(200, 80, 111, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(390, 80, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(10, 140, 47, 13))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(130, 140, 71, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(250, 140, 91, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(550, 140, 81, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(10, 200, 51, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(10, 260, 47, 13))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(10, 320, 47, 13))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(10, 370, 47, 13))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(210, 320, 67, 13))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(210, 260, 101, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(410, 260, 47, 13))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(410, 320, 47, 13))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(600, 320, 47, 13))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(570, 260, 47, 13))
        self.label_18.setObjectName("label_18")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabela = QtWidgets.QTableWidget(self.tab_2)
        self.tabela.setGeometry(QtCore.QRect(0, 0, 771, 371))
        self.tabela.setObjectName("tabela")
        self.tabela.setColumnCount(17)
        self.tabela.setRowCount(100)
        item = QtWidgets.QTableWidgetItem()
        self.tabela.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela.setHorizontalHeaderItem(16, item)
        self.botaoTestar2 = QtWidgets.QPushButton(self.tab_2)
        self.botaoTestar2.setGeometry(QtCore.QRect(420, 390, 221, 23))
        self.botaoTestar2.setObjectName("botaoTestar2")
        self.labelTeste2 = QtWidgets.QLabel(self.tab_2)
        self.labelTeste2.setEnabled(False)
        self.labelTeste2.setGeometry(QtCore.QRect(200, 390, 201, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelTeste2.setFont(font)
        self.labelTeste2.setText("")
        self.labelTeste2.setObjectName("labelTeste2")
        self.botaoListarProdutos = QtWidgets.QPushButton(self.tab_2)
        self.botaoListarProdutos.setGeometry(QtCore.QRect(660, 390, 91, 23))
        self.botaoListarProdutos.setObjectName("botaoListarProdutos")
        #self.botaoDeletarProduto = QtWidgets.QPushButton(self.tab_2)
        #self.botaoDeletarProduto.setGeometry(QtCore.QRect(160, 390, 91, 23))
        #self.botaoDeletarProdutos.setObjectName("botaoDeletarProdutos")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCadastro = QtWidgets.QAction(MainWindow)
        self.actionCadastro.setObjectName("actionCadastro")
        self.actionListar_Produtos = QtWidgets.QAction(MainWindow)
        self.actionListar_Produtos.setObjectName("actionListar_Produtos")
        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "SISTEMA DE CADASTRO DE PRODUTO"))
        self.botaoTestar.setText(_translate("MainWindow", "Testar Conexão com o Banco de Dados"))
        self.botaoCadastrar.setText(_translate("MainWindow", "Cadastrar"))
        self.label_2.setText(_translate("MainWindow", "Codigo do Produto"))
        self.label_3.setText(_translate("MainWindow", "Codigo de Barras"))
        self.label_4.setText(_translate("MainWindow", "Corredor"))
        self.label_5.setText(_translate("MainWindow", "Entrada"))
        self.label_6.setText(_translate("MainWindow", "Vencimento"))
        self.label_7.setText(_translate("MainWindow", "Departamento"))
        self.label_8.setText(_translate("MainWindow", "Fornecedor"))
        self.label_9.setText(_translate("MainWindow", "Descricao"))
        self.label_10.setText(_translate("MainWindow", "Grupo"))
        self.label_11.setText(_translate("MainWindow", "Preco por"))
        self.label_12.setText(_translate("MainWindow", "Unidade"))
        self.label_13.setText(_translate("MainWindow", "Responsavel"))
        self.label_14.setText(_translate("MainWindow", "Id do Funcionario"))
        self.label_15.setText(_translate("MainWindow", "Marca"))
        self.label_16.setText(_translate("MainWindow", "Secao"))
        self.label_17.setText(_translate("MainWindow", "Tipo"))
        self.label_18.setText(_translate("MainWindow", "Preco"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Cadastro"))
        item = self.tabela.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tabela.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Codigo"))
        item = self.tabela.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Codigo de Barras"))
        item = self.tabela.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Corredor"))
        item = self.tabela.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Data de Entrada"))
        item = self.tabela.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Data de Validade"))
        item = self.tabela.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Departamento"))
        item = self.tabela.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Descricao"))
        item = self.tabela.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Fornecedor"))
        item = self.tabela.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Grupo"))
        item = self.tabela.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Id Funcionario"))
        item = self.tabela.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Marca"))
        item = self.tabela.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Preco"))
        item = self.tabela.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Preco por"))
        item = self.tabela.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "Responsavel"))
        item = self.tabela.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "Secao"))
        item = self.tabela.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "Tipo"))
        item = self.tabela.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "Unidade"))
        self.botaoTestar2.setText(_translate("MainWindow", "Testar Conexão com o Banco de Dados"))
        self.botaoTestar2.clicked.connect(self.teste)
        self.botaoTestar.clicked.connect(self.teste)
        self.botaoListarProdutos.setText(_translate("MainWindow", "Listar Produtos"))
        self.botaoListarProdutos.clicked.connect(self.lista_produtos)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Produtos"))
        self.actionCadastro.setText(_translate("MainWindow", "Cadastro"))
        self.actionListar_Produtos.setText(_translate("MainWindow", "Listar Produtos"))
        
    def get_inicial(self):
        r = requests.get('http://www.emporioserrana.tk/api/produtos/cadastrar_produto')
        #Requisição para buscar fornecedores, responsáveis e último produto
    
    def delete(self): 
        r = requests.delete('http://www.emporioserrana.tk/api/produtos/deletar_produto', json = json)
    
    def update(self): 
        r = requests.put('http://www.emporioserrana.tk/api/produtos/update_produto', json = json)

    def cadastrar_produto(self):
        codigo = self.campoCodigo.text()
        codigoBarras = self.campoCodigoBarras.text()
        corredor = self.campoCorredor.text()
        departamento = self.campoDepartamento.text()
        fornecedor = self.campoFornecedor.currentText()
        validadeLote = self.campoDataValidade.text()
        dataEntrada = self.campoDataEntrada.text()
        descricao = self.campoDescricao.text()
        grupo = self.campoGrupo.text()
        idFuncionario = self.campoIdFuncionario.text()
        marca = self.campoMarca.text()
        preco = self.campoPreco.text()
        tipo = self.campoTipo.text()
        secao = self.campoSecao.text()
        responsavel = self.campoResponsavel.currentText()
        precoPor = self.campoPrecoPor.text()
        unidade = self.campoUnidade.text()

        json = {
            "codigo": int(codigo)
        }


        r = requests.post('http://www.emporioserrana.tk/api/produtos/cadastrar_produto', json = json)
        print(r)



    def lista_produtos(self):
        item = QTableWidgetItem

        r = requests.get('http://www.emporioserrana.tk/api/produtos/listar_produtos')
        req = r.json()
        x = int(len(req))
        for produto in range(0, x):
            cont = 0
            for coluna in req[produto]:
                i = req[produto][coluna]
                self.tabela.setItem(produto, cont, item(str(i)))
                cont += 1

    def teste(self):
        try:
            requests.get('http://www.emporioserrana.tk/api')
            self.labelTeste.setText("Sucesso na conexão!")
            self.labelTeste2.setText("Sucesso na conexão!")
        except ConnectionError:
            self.labelTeste.setText("Erro na conexão!")
            self.labelTeste2.setText("Erro na conexão!")

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())